/**
 * Skill Taxonomy & Categorization Reference
 *
 * Provides a reference taxonomy for organizing skills.
 * IMPORTANT: This taxonomy is NOT a hard limit.
 * Any novel/unknown skill extracted from user data is preserved and categorized as "Other".
 */

import { SkillCategory } from "@/types/verification";

const CATEGORY_MAP: Record<string, SkillCategory> = {
  // Programming Languages
  python: "Programming",
  javascript: "Programming",
  typescript: "Programming",
  java: "Programming",
  c: "Programming",
  "c++": "Programming",
  "c#": "Programming",
  go: "Programming",
  golang: "Programming",
  rust: "Programming",
  php: "Programming",
  kotlin: "Programming",
  swift: "Programming",
  dart: "Programming",
  ruby: "Programming",
  r: "Programming",
  scala: "Programming",
  bash: "Programming",
  shell: "Programming",
  "shell scripting": "Programming",
  powershell: "Programming",
  lua: "Programming",
  perl: "Programming",
  haskell: "Programming",
  elixir: "Programming",
  clojure: "Programming",
  groovy: "Programming",
  julia: "Programming",
  solidity: "Programming",
  assembly: "Programming",

  // Frontend
  html: "Frontend",
  css: "Frontend",
  react: "Frontend",
  angular: "Frontend",
  vue: "Frontend",
  "vue.js": "Frontend",
  "next.js": "Frontend",
  nuxt: "Frontend",
  gatsby: "Frontend",
  remix: "Frontend",
  svelte: "Frontend",
  "tailwind css": "Frontend",
  tailwind: "Frontend",
  bootstrap: "Frontend",
  sass: "Frontend",
  scss: "Frontend",
  redux: "Frontend",
  zustand: "Frontend",
  mobx: "Frontend",
  "material ui": "Frontend",
  "chakra ui": "Frontend",
  "shadcn/ui": "Frontend",
  shadcn: "Frontend",
  "framer motion": "Frontend",
  webpack: "Frontend",
  vite: "Frontend",
  rollup: "Frontend",
  storybook: "Frontend",

  // Backend
  "node.js": "Backend",
  node: "Backend",
  "express.js": "Backend",
  express: "Backend",
  django: "Backend",
  flask: "Backend",
  fastapi: "Backend",
  spring: "Backend",
  "spring boot": "Backend",
  springboot: "Backend",
  laravel: "Backend",
  symfony: "Backend",
  "rest apis": "Backend",
  "rest api": "Backend",
  rest: "Backend",
  graphql: "Backend",
  grpc: "Backend",
  websockets: "Backend",
  websocket: "Backend",
  fastify: "Backend",
  nestjs: "Backend",
  "ruby on rails": "Backend",
  rails: "Backend",
  ".net": "Backend",
  "asp.net": "Backend",
  gin: "Backend",
  fiber: "Backend",
  axum: "Backend",
  actix: "Backend",

  // Databases
  mysql: "Database",
  postgresql: "Database",
  postgres: "Database",
  mongodb: "Database",
  sqlite: "Database",
  redis: "Database",
  oracle: "Database",
  sql: "Database",
  mssql: "Database",
  "sql server": "Database",
  mariadb: "Database",
  cassandra: "Database",
  dynamodb: "Database",
  firebase: "Database",
  firestore: "Database",
  supabase: "Database",
  neo4j: "Database",
  elasticsearch: "Database",
  prisma: "Database",
  typeorm: "Database",
  mongoose: "Database",
  drizzle: "Database",

  // Data / AI / ML
  numpy: "Data & AI",
  pandas: "Data & AI",
  matplotlib: "Data & AI",
  seaborn: "Data & AI",
  "scikit-learn": "Data & AI",
  sklearn: "Data & AI",
  tensorflow: "Data & AI",
  pytorch: "Data & AI",
  keras: "Data & AI",
  opencv: "Data & AI",
  nlp: "Data & AI",
  "natural language processing": "Data & AI",
  "computer vision": "Data & AI",
  "machine learning": "Data & AI",
  ml: "Data & AI",
  "deep learning": "Data & AI",
  dl: "Data & AI",
  "data analysis": "Data & AI",
  "data visualization": "Data & AI",
  llm: "Data & AI",
  "large language models": "Data & AI",
  "generative ai": "Data & AI",
  langchain: "Data & AI",
  llamaindex: "Data & AI",
  "hugging face": "Data & AI",
  transformers: "Data & AI",
  mlops: "Data & AI",
  "apache spark": "Data & AI",
  spark: "Data & AI",
  hadoop: "Data & AI",
  "apache kafka": "Data & AI",
  kafka: "Data & AI",
  "apache airflow": "Data & AI",
  airflow: "Data & AI",
  dbt: "Data & AI",
  tableau: "Data & AI",
  "power bi": "Data & AI",
  excel: "Data & AI",

  // Cloud & DevOps
  aws: "Cloud & DevOps",
  azure: "Cloud & DevOps",
  "microsoft azure": "Cloud & DevOps",
  gcp: "Cloud & DevOps",
  "google cloud": "Cloud & DevOps",
  docker: "Cloud & DevOps",
  kubernetes: "Cloud & DevOps",
  k8s: "Cloud & DevOps",
  "github actions": "Cloud & DevOps",
  "ci/cd": "Cloud & DevOps",
  cicd: "Cloud & DevOps",
  linux: "Cloud & DevOps",
  terraform: "Cloud & DevOps",
  ansible: "Cloud & DevOps",
  jenkins: "Cloud & DevOps",
  nginx: "Cloud & DevOps",
  apache: "Cloud & DevOps",
  prometheus: "Cloud & DevOps",
  grafana: "Cloud & DevOps",
  cloudflare: "Cloud & DevOps",
  serverless: "Cloud & DevOps",

  // Software Engineering
  git: "Software Engineering",
  github: "Software Engineering",
  gitlab: "Software Engineering",
  bitbucket: "Software Engineering",
  jira: "Software Engineering",
  testing: "Software Engineering",
  "unit testing": "Software Engineering",
  debugging: "Software Engineering",
  "object-oriented programming": "Software Engineering",
  oop: "Software Engineering",
  "data structures": "Software Engineering",
  dsa: "Software Engineering",
  algorithms: "Software Engineering",
  "system design": "Software Engineering",
  jest: "Software Engineering",
  vitest: "Software Engineering",
  cypress: "Software Engineering",
  playwright: "Software Engineering",
  selenium: "Software Engineering",
  postman: "Software Engineering",
  agile: "Software Engineering",
  scrum: "Software Engineering",
  tdd: "Software Engineering",

  // Cybersecurity
  "network security": "Cybersecurity",
  "web security": "Cybersecurity",
  owasp: "Cybersecurity",
  "ethical hacking": "Cybersecurity",
  cryptography: "Cybersecurity",
  "penetration testing": "Cybersecurity",
  wireshark: "Cybersecurity",
  "kali linux": "Cybersecurity",
  "burp suite": "Cybersecurity",

  // Mobile
  android: "Mobile",
  "android studio": "Mobile",
  flutter: "Mobile",
  "react native": "Mobile",
  ios: "Mobile",
  swiftui: "Mobile",
  "jetpack compose": "Mobile",
  expo: "Mobile",
  ionic: "Mobile",

  // UI/UX & Design
  figma: "UI/UX & Design",
  "adobe xd": "UI/UX & Design",
  photoshop: "UI/UX & Design",
  illustrator: "UI/UX & Design",
  "ui design": "UI/UX & Design",
  "ux design": "UI/UX & Design",
  prototyping: "UI/UX & Design",
  wireframing: "UI/UX & Design",
  "design systems": "UI/UX & Design",
};

/**
 * Determine category for a normalized skill name.
 * Defaults to "Other" for novel/unknown technologies to preserve them.
 */
export function categorizeSkill(skillName: string): SkillCategory {
  const normalizedKey = skillName.trim().toLowerCase();
  return CATEGORY_MAP[normalizedKey] ?? "Other";
}
